swagger: "2.0"
info:
  description: "Food deliveri api documentation"
  version: "1.0.0"
  title: "FoodDeliveri API"
  contact:
    email: "skateray17@gmail.com"
host: "localhost:3000"
tags:
- name: "authentication"
  description: "Everything about authentication"
- name: "order"
  description: "Access to Petstore orders"
schemes:
- "http"
basePath: "/api"
paths:
  /account/logon:
    post:
      tags:
      - "authentication"
      summary: "logon an user"
      description: "service for logon"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"

      parameters:
      - in: "body"
        name: "body"
        description: "Needs email and password"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"
      responses:
        401:
          description: "Invalid input"
        200:
          description: "Successful logon"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
  /account/logoff:
    post:  
      tags:
        - "authentication"
      summary: "logoff an user"
      description: "It just return success, but tokem should be removed on front side"
      responses:
        200:
          description: "Successfull operation"
  /order/getUserOrders:
    get:
      tags:
      - "order"
      description: "return all orders of current user"
      parameters:
      - in: "query"
        name: "username"
        required: true
        type: "string"
      responses:
        500:
          description: "No such user or some error happend"
        200:
          description: "Successful logon"
          schema:
            type: "object"
            properties:
              result:
                type: "array"
                items:
                  type: "object"
                  properties:
                    date:
                      type: "string"
                    order:
                      type: "object"
                      properties:
                        _id:
                          type: "string"
                        username:
                          type: "string"
                        dishList:
                          type: "array"
                          items:
                            type: "object"
                            properties:
                              _id:
                                type: "string"
                              dishTitle:
                                type: "string"
                              amount:
                                type: "integer"
                        totalPrice:
                          type: "number"